ci/setup slack alerts (#7)
* ci: add Slack notifications for pipeline job status

* ci: add Slack notifications for pipeline job status

* ci: add Slack notifications for pipeline job status

* ci: add Slack notifications for pipeline job status

* ci: test Slack notifications for pipeline job status

* ci: test Slack notifications for pipeline job status

* ci: test Slack notifications for pipeline job status

* ci: test Slack notifications for pipeline job status

* ci: test Slack notifications for pipeline job status

* ci: add Allure report regeneration command in CI

* ci: add Allure report regeneration command in CI

* feat: add attached screenshot on afterTest hooks

* ci: update android test workflow

* ci: update android test workflow

* ci: update android test workflow

* ci: update android test workflow

* ci: update android test workflow

* ci: update android test workflow

* feat: add allure config file

* ci: correct commit link url for slack

* ci: correct commit link url for slack

* ci: correct commit link url for slack

* ci: update workflow and wdio configuration file

* chore: create directory for failed test cases

* chore: support --spec argument for WDIO test execution

* ci: modify github  workflow file

* ci: modify github workflow file

* ci: modify github workflow file

* ci: modify github workflow file

* ci: modify github workflow file

* ci: testing github workflow file

* ci: testing github workflow file

* ci: testing github workflow file

* ci: testing github workflow file

* chore: update afterTest hook in wdio config file

* chore: update afterTest hook in wdio config and workflow file

* chore: update afterTest hook in wdio config and workflow file

* chore: update afterTest hook in wdio config and workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android-tests workflow file

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

* ci: testing android tests workflow

---------

Co-authored-by: Rome <jerome.encinares@apolloglobal.net>

diff --git a/.github/workflows/android-test.yaml b/.github/workflows/android-test.yaml
--- a/.github/workflows/android-test.yaml
+++ b/.github/workflows/android-test.yaml
@@ -3,7 +3,7 @@ name: Android Emulator Tests
 on:
   push:
     branches:
-      - ci/android-test-workflow
+      - ci/setup-slack-alerts
 
 env:
   DOTENV_CONFIG_QUIET: true
@@ -11,6 +11,8 @@ env:
   STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
   LOCKED_OUT_USER: ${{ secrets.LOCKED_OUT_USER }}
   LOCKED_OUT_PASSWORD: ${{ secrets.LOCKED_OUT_PASSWORD }}
+  ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
 
 jobs:
   android-tests:
@@ -25,9 +27,9 @@ jobs:
         uses: actions/checkout@v5
 
       - name: Setup Node.js
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v6
         with:
-          node-version: 22
+          node-version: 24
           cache: npm
 
       - name: Install dependencies
@@ -56,7 +58,7 @@ jobs:
           api-level: 34
           target: google_apis
           arch: x86_64
-          profile: pixel_7
+          profile: pixel_6
           disable-animations: true
           emulator-options: >-
             -no-window
@@ -64,6 +66,9 @@ jobs:
             -noaudio
             -no-boot-anim
             -no-snapshot
+            -camera-front none
+            -camera-back none
+            -no-metrics
           script: |
             adb wait-for-device
             adb devices
@@ -75,23 +80,211 @@ jobs:
             echo "Running WDIO tests..."
             npm run wdio
 
+      - name: Extract Allure summary
+        if: always()
+        id: allure
+        run: |
+          sudo apt-get update && sudo apt-get install -y jq
+
+          PASSED=$(find allure-results -name "*.json" -exec jq '.status' {} \; | grep -c "passed" || true)
+          FAILED=$(find allure-results -name "*.json" -exec jq '.status' {} \; | grep -c "failed" || true)
+          BROKEN=$(find allure-results -name "*.json" -exec jq '.status' {} \; | grep -c "broken" || true)
+
+          echo "passed=$PASSED" >> $GITHUB_OUTPUT
+          echo "failed=$FAILED" >> $GITHUB_OUTPUT
+          echo "broken=$BROKEN" >> $GITHUB_OUTPUT
+
+      - name: Prepare Temporary GitHub Pages
+        if: always()
+        run: mkdir -p ./temp-gh-pages
+
+      - name: Checkout gh-pages Branch
+        if: always()
+        continue-on-error: true
+        uses: actions/checkout@v4
+        with:
+          ref: gh-pages
+          path: gh-pages
+
+      - name: Restore Allure History
+        if: always()
+        run: |
+          mkdir -p allure-results
+          mkdir -p prev-allure-history
+
+          if [ -f "gh-pages/allure-history/history.jsonl" ]; then
+            cat gh-pages/allure-history/history.jsonl
+            echo "Found history.jsonl"
+
+            cat gh-pages/allure-history/history.jsonl >> prev-allure-history/history.jsonl && printf '\n' >> prev-allure-history/history.jsonl
+            echo "copying allure history done."
+
+            cat prev-allure-history/history.jsonl
+            echo "Reading previous history done."
+          else
+            echo "No previous history found."
+          fi
+
+      - name: Restore Previous Allure Results
+        if: always()
+        run: |
+          if [ -d "gh-pages/allure-results" ] && \
+             [ "$(find gh-pages/allure-results -type f | wc -l)" -gt 0 ]; then
+             
+            echo "Found previous allure-results"
+            cp -R gh-pages/allure-results/. allure-results/
+
+            cp -R prev-allure-history/history.jsonl allure-results/
+            echo "copying allure history done."
+          else
+            echo "No previous allure-results found."
+          fi
+
       - name: Generate Allure Report
         if: always()
         run: npm run allure:generate
 
-      - name: Upload Allure Report
+      - name: List Files
         if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-report
-          path: allure-report
-          retention-days: 30
+        run: ls -R
 
-      - name: Deploy Allure Report to GitHub Pages
+      - name: List All Branch
+        if: always()
+        run: git branch -a
+
+      - name: Copy Files to temp-gh-pages
+        if: always()
+        run: |
+          [ -d "allure-results" ] && cp -R allure-results temp-gh-pages/
+          [ -f "prev-allure-history/history.jsonl" ] && cat prev-allure-history/history.jsonl >> prev-allure-history/history.jsonl && printf '\n' >> allure-history/history.jsonl
+          [ -d "allure-history" ] && cp -R allure-history temp-gh-pages/
+          [ -d "allure-report" ] && cp -R allure-report temp-gh-pages/
+
+      - name: List Files in temp-gh-pages
+        if: always()
+        run: ls -R ./temp-gh-pages
+
+      - name: Deploy to GitHub Pages
         if: always()
         uses: peaceiris/actions-gh-pages@v4
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
-          publish_dir: allure-report
-          keep_files: false
+          publish_dir: ./temp-gh-pages
+          keep_files: true
+
+      - name: Set Short SHA
+        if: always()
+        id: vars
+        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Notify Slack on Failure
+        if: failure()
+        uses: slackapi/slack-github-action@v2.0.0
+        with:
+          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
+          webhook-type: incoming-webhook
+          payload: |
+            {
+              "attachments": [
+                {
+                  "color": "#FF0000",
+                  "blocks": [
+                    {
+                      "type": "header",
+                      "text": {
+                        "type": "plain_text",
+                        "text": "🚀 CI Mobile Test Automation Build Failed"
+                      }
+                    },
+                    {
+                      "type": "section",
+                      "fields": [
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Repo Name:*\n:git-branch-white: <https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}|${{ github.event.repository.name }}>"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Build Run:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}>"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Commit:*\n:git-commit: <https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/commit/${{ github.sha }}|${{ steps.vars.outputs.sha_short }}> :delete:"
+                        },
+                        {
+                          "type": "mrkdwn",
+                           "text": "*Commit by:*\n:github-white: ${{ github.event.head_commit.author.name }}"
+                        }
+                      ]
+                    },
+                  ]
+                }
+              ]
+              }
+
+      - name: Notify Slack on Success
+        if: success()
+        uses: slackapi/slack-github-action@v2.0.0
+        with:
+          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
+          webhook-type: incoming-webhook
+          payload: |
+            {
+              "attachments": [
+                {
+                  "color": "#2EB67D",
+                  "blocks": [
+                    {
+                      "type": "header",
+                      "text": {
+                        "type": "plain_text",
+                        "text": "🚀 CI Mobile Test Automation Build Succeeded"
+                      }
+                    },
+                    {
+                      "type": "section",
+                      "fields": [
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Repo Name:*\n:git-branch-white: <https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}|${{ github.event.repository.name }}>"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Build Run:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}>"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Commit:*\n:git-commit: <https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/commit/${{ github.sha }}|${{ steps.vars.outputs.sha_short }}> :check:"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Commit by:*\n:github-white: ${{ github.event.head_commit.author.name }}"
+                        }
+                      ]
+                    },
+                    {
+                      "type": "section",
+                      "text": {
+                        "type": "mrkdwn",
+                        "text": "*Results*\n• *Passed:* ${{ steps.allure.outputs.passed }}\n• *Failed:* ${{ steps.allure.outputs.failed }}\n• *Broken:* ${{ steps.allure.outputs.broken }}"
+                      }
+                    },
+                    {
+                      "type": "actions",
+                      "elements": [
+                        {
+                          "type": "button",
+                          "text": {
+                            "type": "plain_text",
+                            "text": ":allure-logo: Allure Report"
+                          },
+                          "url": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/",
+                          "style": "primary"
+                        }
+                      ]
+                    }
+                  ]
+                }
+              ]
+            }
